# Generated by Django 5.2 on 2025-05-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField()),
                ('from_station', models.IntegerField()),
                ('destination_station', models.IntegerField()),
                ('trainid', models.IntegerField()),
                ('boarding_date', models.DateField()),
                ('no_of_passengers', models.IntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
