# Build stage
FROM eclipse-temurin:21-jdk-jammy AS builder
WORKDIR /spring-app

COPY .mvn/ .mvn
COPY ./mvnw pom.xml ./
RUN ./mvnw dependency:go-offline

COPY src ./src
RUN ./mvnw clean install

# Runtime stage
FROM eclipse-temurin:21-jre-jammy AS final
WORKDIR /opt/app
EXPOSE 8080

COPY --from=builder /spring-app/target/*.jar /opt/app/app.jar

ENTRYPOINT ["java", "-jar", "/opt/app/app.jar"]